import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Homepage</Link>
        </li>
        <li>
          <Link to="/dichvuone">DichvuOne</Link>
        </li>
        <li>
          <Link to="/tinmoione">TinmoiOne</Link>
        </li>
        <li>
          <Link to="/cohoinghenghiep">Cohoinghenghiep</Link>
        </li>
        <li>
          <Link to="/vechungtoi">Vechungtoi</Link>
        </li>
        <li>
          <Link to="/doitackhachhang">Doitackhachhang</Link>
        </li>
        <li>
          <Link to="/dichvu">Dichvu</Link>
        </li>
        <li>
          <Link to="/tinmoi">Tinmoi</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
